### ISSUE TITLE
WDefaultButton의 font 크기 변경

### ISSUE THREAD

**Issue by llghdud921** [YAPP-Github/20th-ALL-Rounder-Team-1-iOS#11]
### 현재 동작:
WDefaultButton의 font 크기가 변경되지 않습니다. IOS15부터 지원되는 ConfigurationButton 스터디 후 개선 예정입니다.
![스크린샷 2022-05-26 오전 12 54 15](https://user-images.githubusercontent.com/40068674/170305252-ca0aa383-78bb-4c93-835a-c142b9b58b14.png)

---

### 기대 동작:
WDefaultButton의 font 크기 수정

---

**Comment by ChoiysApple** [comment]
### 원인
```swift
self.titleLabel?.font = UIFont(name: "PretendardVariable-Medium", size: defaultFontSize)
```
> `iOS 15`로 넘어오면서 `UIButton.Configuration`으로 바뀌면서 `titleLabel` 구문이 제대로 작동하지 않음


### 해결

<img width="267" alt="image" src="https://user-images.githubusercontent.com/43776784/170429440-4976fe78-5588-458f-818c-bc03abb92e05.png">


> `titleLabel?.font` 를 지정해주는 대신, `setTitle(_:for:)`를 오버라이드 해서 `NSAttributedString`을 입력해주는 방식으로 구현

```swift
// WDefaultButton.swift
    override func setTitle(_ title: String?, for state: UIControl.State) {
        super.setTitle(title, for: state)
        
        guard let text = title else { return }
        let attribute = [NSAttributedString.Key.font: UIFont(name: "PretendardVariable-Medium", size: defaultFontSize)]
        let attributedTitle = NSAttributedString(string: text, attributes: attribute as [NSAttributedString.Key : Any])
        self.setAttributedTitle(attributedTitle, for: .normal)
    }
```


### 참고 문헌
https://minios.tistory.com/6
