### ISSUE TITLE
[Refactor] Network - 쿼리파일 이름 변경

### ISSUE THREAD

**Issue by ChoiysApple** [YAPP-Github/20th-ALL-Rounder-Team-1-iOS#128]
`*.graphql`파일의 파일명을 `PascalCase`로 일관되게 수정

**Comment by llghdud921** [comment]
### 구현 완료
<img src="https://user-images.githubusercontent.com/40068674/182784579-7274cd3d-074d-4196-8381-cf4e8c7feb1b.png" width="200" height="400">
쿼리 파일 명 Pascal case로 네이밍 개선 후 폴더 구조화 하였습니다

![스크린샷 2022-08-04 오후 4 05 35](https://user-images.githubusercontent.com/40068674/182784914-21a4312c-d595-4a3e-a43d-d1141c66fd69.png)
추가로 폴더 구조 변경으로 인한 `apollo` `build setting` -> `input file` 설정을 변경하였습니다
