### ISSUE TITLE
[Fix] SearchScene - 정렬 유형 default 수정

### ISSUE THREAD

**Issue by ChoiysApple** [YAPP-Github/20th-ALL-Rounder-Team-1-iOS#188]
현재 `최신순`이 default
-> `팔로워순`을 default로 수정

**Comment by llghdud921** [comment]
<img src="https://user-images.githubusercontent.com/40068674/182769741-8620d85c-00d3-4cb4-9e4d-8428ffd7aade.png" width="200" height="400">

적용 완료
