### ISSUE TITLE
[Fix] iOS 14 환경에서 Navigation 디자인이 다르게 적용되는 문제

### ISSUE THREAD

**Issue by ChoiysApple** [YAPP-Github/20th-ALL-Rounder-Team-1-iOS#48]
## 버그 설명
`iOS 14`에서 NavigationBar 배경 & 테두리가 보인다

## 현재 동작
`iOS 14` `iPhone 11`

<img src="https://user-images.githubusercontent.com/43776784/173473449-8bd56f39-e5cb-41bd-ae6d-ef4f2f4487aa.png" width=200>

## 기대 동작
`iOS 15` `iPhone 12 mini`

<img src="https://user-images.githubusercontent.com/43776784/173473705-1d471d6d-22e8-41c4-9953-917f831bb904.jpeg" width="200">

## 해당 버그를 발생시키는 방법
`iOS 14`환경에서 실행

**Comment by llghdud921** [comment]
### 원인
ios 15로 업데이트 되면서 navigationBar 설정이 바뀌게 되면서 navigation bar가 투명한 배경으로 생성이 되게 되었는데
ios 14에서는 색상이 설정이 되어 생긴 문제였습니다

### 해결 방법
ios13부터 사용가능한 UINavigationBarAppearance을 이용해 투명한 색상으로 적용하였습니다
