### ISSUE TITLE
[Fix] Resources - Asset 아이콘 파일 변경

### ISSUE THREAD

**Issue by ChoiysApple** [YAPP-Github/20th-ALL-Rounder-Team-1-iOS#57]
### 변경한 아이콘 체크
> 기존 크기가 큰 아이콘을 크기가 작은 아이콘으로 변경했는지 확인하기 위한 Issue
> 아이콘 파일이 변경될 때 마다 해당 항목 체크합니다

`arrows`
- [x] arrow.down
- [x] arrow.left
- [x] arrow.right
- [x] back
- [x] chevron.down
- [ ] chevron.right (미사용)
- [x] chevron.up

</br>

`Button`
- [x] category.update
- [x] close
- [x] edit
- [x] folder.plus
- [x] plus.circle.fill
- [ ] plus (미사용)
- [ ] setting (미사용)

</br>

`Information`
- [x] alarm
- [ ] date.end (미사용)
- [ ] date.start (미사용)
- [x] search
- [ ] visibility.disabled (미사용)
- [ ] visibility (미사용)

</br>

`State`
- [x] state.completed
- [x] state.hold
- [x] state.proceeding
- [x] state.skipped
- [x] state.upcomming

</br>

`User Input`
- [x] checkmark.fill
- [x] radio.disabled
- [x] radio.enabled

**Comment by llghdud921** [comment]
![스크린샷 2022-08-04 오후 3 21 31](https://user-images.githubusercontent.com/40068674/182777253-e33082db-1ab4-4217-9ee8-0074550a458d.png)

사용되지 않는 아이콘 외 모두 적용 완료
