### ISSUE TITLE
ColorSheet 가운데 정렬

### ISSUE THREAD

**Issue by ChoiysApple** [YAPP-Github/20th-ALL-Rounder-Team-1-iOS#73]
## 버그 설명
ColorSheet의 색상 팔레트 CollectionView가 한쪽으로 치우쳐 있음

## 현재 동작
<img width="300" src="https://user-images.githubusercontent.com/43776784/177758228-be2ba916-5461-47fc-af84-42e3469cb25b.png">

## 기대 동작
<img width="300" src="https://user-images.githubusercontent.com/43776784/177758475-6e291c71-a38d-4aa1-a6f5-b95f13b230a0.png">

**Comment by llghdud921** [comment]
![simulator_screenshot_35ED64DF-D1EF-4AC0-847B-E51D8514D890](https://user-images.githubusercontent.com/40068674/178289048-c2a831c6-bf59-4395-8836-aec657885ad9.png)

기기별 크기 대응하여 sheet 구성
